# This official base image contains node.js and npm

FROM node:7

ARG VERSION=1.0.0

# Copy the application files

WORKDIR /usr/src/app

COPY package.json app.js LICENSE /usr/src/app/

COPY lib /usr/src/app/lib/

LABEL license=MIT \

      version=$VERSION

# Set required environment variables

ENV NODE_ENV production

# Download the required packages for production

RUN npm update

# Make the application run when running the container

CMD ["node", "app.js"]